### ISSUE TITLE
Visual bug with map names text

### ISSUE THREAD

**Issue by Jedayr** [John-Paul-R/PoE-Atlas-Website#32]
Basically i just clicked around as mad around this region, clicked at maps/tiers and then this happened.

![image](https://user-images.githubusercontent.com/17459615/95291718-d0f8dc00-0878-11eb-9a64-8633c7285ef9.png)

*Probably* it was tier 4 tirn's end. 
I was able to reproce this bug in incognito tab with promenade map after ~lot clicking at this map in tier 4 region.

![image](https://user-images.githubusercontent.com/17459615/95292750-c2132900-087a-11eb-8235-1721f4e1b866.png)

 
My browser data: 

Vivaldi | 2.10.1745.27 (Stable channel) (64 bit)

Version | 0cff17186b317ac1935c017269c5e1e8c4620320

OS | Windows 10 OS Version 1809 (Build 17763.1397)

JavaScript | V8 7.9.317.33

**Comment by John-Paul-R** [comment]
Interesting, I'll look into this. Thanks for the report!

**Comment by John-Paul-R** [comment]
Made some headway in identifying the cause of the issue. This is a combination of 2 bugs.

There is a way to get the map in a state where it acts as if the mouse is dragging, even if its mousedown is not being held. (Not sure exactly what causes this)

If the interface is in this state and you mousedown on a map node, then mouseup outside that map node, the map selection issue will occur.

**Comment by John-Paul-R** [comment]
The map gets in the "dragging while not actually dragging" state when you double click and then attempt to click-drag. I believe this is because the canvas element has essentially been "highlighted" (as you would text), and then the click-drag is using the built-in "copy by dragging highlighted element" gesture.

Will confirm if this is indeed the issue. If it is, I'll look into disabling highlighting of the canvas in this way.
